// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 the swift-wire project authors

import Foundation

// Stands in for WireGen's consumer half. Arguments: <output.swift> <manifest…>.
//
// It reads each candidate manifest and bakes the result into a generated
// constant, so the assertion happens in the *built product* rather than in
// build log text — a gate that greps build output passes when the command
// silently stops running.
let arguments = CommandLine.arguments
let outputPath = arguments[1]
let candidates = Array(arguments.dropFirst(2))

var readings: [String] = []
for candidate in candidates {
    if let contents = try? String(contentsOfFile: candidate, encoding: .utf8) {
        readings.append(contents.trimmingCharacters(in: .whitespacesAndNewlines))
        FileHandle.standardError.write("ConsumerGen: read \(candidate)\n".data(using: .utf8)!)
    } else {
        FileHandle.standardError.write("ConsumerGen: MISSING \(candidate)\n".data(using: .utf8)!)
    }
}

let literals = readings.map { "#\"\($0)\"#" }.joined(separator: ", ")
try """
// Generated by ConsumerGen from the dependency's plugin output.
let manifestsReadAtBuildTime: [String] = [\(literals)]

""".write(toFile: outputPath, atomically: true, encoding: .utf8)
