import Wire
import WireHarnessLibrary

/// A consumer `@Singleton` that injects the external library's bindings
/// across the package boundary — both the unkeyed `@Singleton` and the
/// keyed `@Provides(ExternalService.primary)`.
@Singleton(allowUnused: true)
struct App {
    @Inject var service: ExternalService
    @Inject(ExternalService.primary) var primary: ExternalService
}

/// A graph conformance over the library's key — the consumer declares the protocol and the mapping, the
/// library contributes. This is the root that keeps an aggregate alive with no `@Inject` consumer, and its
/// failure mode is silent: a member whose key has no aggregate falls back to an empty collection, so a
/// pruned aggregate compiles and serves nothing. The assertion below is behavioural for that reason.
protocol HarnessComposable {
    var contributors: [any HarnessRouteContributor] { get }
}

enum HarnessComposableConformance {
    static let decl = WireGraphConformanceV1(
        conformsTo: (any HarnessComposable).self,
        members: [.init("contributors", from: HarnessRouteKeys.contributors)]
    )
}

// `_WireGraph` is generated by WireBuildPlugin running on this target; it
// composes the consumer's own bindings with the activated external
// library's. Bootstrapping and reading the values proves the external
// `.product` activation path (7d), the foreign `import` (7c), and
// cross-module key resolution (7a/7f) end-to-end across a package boundary.
let graph = try await Wire.bootstrap()
precondition(graph.app.service.name == "external", "unkeyed external binding did not compose")
precondition(graph.app.primary.name == "external", "keyed external binding did not compose")

// M7b.2 — reachability pruning. `UnreachedExternalService` traps on construction, so reaching this line at
// all is the assertion that it was pruned: nothing injects it and a library's `allowUnused` is ignored.
print("OK: unreached external binding was pruned (it would have trapped on construction)")

// The conformance-rooted aggregate survives pruning even though nothing `@Inject`s it, and it carries its
// external contributor with it. Empty here would mean the aggregate was pruned and the member fell back to
// its empty accessor — the silent failure a build-only gate cannot see.
let composable: any HarnessComposable = graph
precondition(
    composable.contributors.map(\.label) == ["external-route"],
    "conformance-rooted aggregate lost its external contributor to pruning"
)
print("OK: conformance-rooted aggregate kept its external contributor")
print("OK: composed unkeyed + keyed ExternalService from external package")
