import Wire
import WireHarnessLibrary

/// A consumer `@Singleton` that injects the external library's bindings
/// across the package boundary — both the unkeyed `@Singleton` and the
/// keyed `@Provides(ExternalService.primary)`.
@Singleton(allowUnused: true)
struct App {
    @Inject var service: ExternalService
    @Inject(ExternalService.primary) var primary: ExternalService
}

/// A graph conformance over the library's key — the consumer declares the protocol and the mapping, the
/// library contributes. This is the root that keeps an aggregate alive with no `@Inject` consumer, and its
/// failure mode is silent: a member whose key has no aggregate falls back to an empty collection, so a
/// pruned aggregate compiles and serves nothing. The assertion below is behavioural for that reason.
protocol HarnessComposable {
    var contributors: [any HarnessRouteContributor] { get }
}

enum HarnessComposableConformance {
    static let decl = WireGraphConformanceV1(
        conformsTo: (any HarnessComposable).self,
        members: [.init("contributors", from: HarnessRouteKeys.contributors)]
    )
}

/// The transitive-activation gate. `WireHarnessTransitive` declares a binding of this same simple
/// name, and Wire keys bindings by simple type name — so if that package were activated, the merged graph
/// would carry two `HarnessSharedService` bindings and fail with a duplicate-binding error. The consumer
/// depends on it only *transitively*, through `WireHarnessLibrary`, and transitive dependencies are not
/// activated. Building at all is half the assertion; the `origin` read below is the other half.
@Singleton(allowUnused: true)
struct HarnessSharedService {
    let origin = "consumer"
}

/// The home-module pruning gate — a *home*-module binding nothing reaches, declared right here in the consumer.
///
/// It lives in the harness rather than in `Tests/IntegrationTests` because the pruning warning fires at
/// every visibility, so a deliberately-unreached fixture inside the test corpus would warn on every build.
/// Here the warning is not noise, it is half the assertion: `run-harness.sh` greps the build for it, and
/// construction traps, so the two halves cover the message and the behaviour.
@Singleton
struct UnreachedHomeBinding {
    @Inject
    init() {
        fatalError("UnreachedHomeBinding was constructed — reachability pruning should have dropped it")
    }
}

// `_WireGraph` is generated by WireBuildPlugin running on this target; it
// composes the consumer's own bindings with the activated external
// library's. Bootstrapping and reading the values proves the external
// `.product` activation path (7d), the foreign `import` (7c), and
// cross-module key resolution (7a/7f) end-to-end across a package boundary.
let graph = try await Wire.bootstrap()
precondition(graph.app.service.name == "external", "unkeyed external binding did not compose")
precondition(graph.app.primary.name == "external", "keyed external binding did not compose")

// Reachability pruning. `UnreachedExternalService` traps on construction, so reaching this line at
// all is the assertion that it was pruned: nothing injects it and a library's `allowUnused` is ignored.
print("OK: unreached external binding was pruned (it would have trapped on construction)")

// The conformance-rooted aggregate survives pruning even though nothing `@Inject`s it, and it carries its
// external contributor with it. Empty here would mean the aggregate was pruned and the member fell back to
// its empty accessor — the silent failure a build-only gate cannot see.
let composable: any HarnessComposable = graph
precondition(
    composable.contributors.map(\.label) == ["external-route"],
    "conformance-rooted aggregate lost its external contributor to pruning"
)
print("OK: conformance-rooted aggregate kept its external contributor")

// The transitive package stayed out. A duplicate-binding error would have failed the build
// before this ran; reading the consumer's own value proves which binding is in the graph.
precondition(
    graph.harnessSharedService.origin == "consumer",
    "a transitively-depended Wire-aware package was activated: \(graph.harnessSharedService.origin)"
)
print("OK: transitive Wire-aware package was not activated")

// A library binding whose own dependency lives in a package this consumer never depended on
// (`LibraryBindingNeedingDeep` needs `DeepConfig`). Nothing here reaches it, so reachability strips it
// before the missing-binding check. Reaching this line means that unresolvable binding was a non-event,
// which is exactly what had to be true before the marker could be retired.
print("OK: an unreachable library binding with an unresolvable dependency did not fail the build")

// The home-module half. Same shape as the library one above: `UnreachedHomeBinding` traps on
// construction, so reaching this line is the assertion that it was pruned from the consumer's own graph.
print("OK: unreached home binding was pruned (it would have trapped on construction)")
print("OK: composed unkeyed + keyed ExternalService from external package")
