/// Render the `_WireGraph.swift` source the build plugin writes
/// alongside the consumer target. The generated file contains:
///
/// - The `_WireGraph` struct with one stored property per binding,
///   named by `lowerCamelCased(sanitize(boundType))`.
/// - A `Wire` façade enum whose `bootstrap()` delegates to a free
///   `_wireBootstrap()` at module scope (with `bootstrap<Container>()` /
///   `bootstrap<Scope>Scope(...)` variants for the other graphs).
/// - `_wireBootstrap()` performs the actual construction.
///
/// Why the free function: if construction ran inside a method on
/// `_WireGraph`, Swift name lookup would check the struct's members
/// before module scope. A stored property named `appName` would shadow
/// the user's module-scope `@Provides let appName` and the compiler
/// would error with "instance member cannot be used on type." The free
/// function at module scope has no enclosing type, so bare references
/// resolve straight to module scope, sidestepping the shadow entirely;
/// the `Wire` façade just forwards to it.
///
/// Inside the free function, bare local names are safe even when they
/// equal a module-scope identifier — Swift's `let x = x` resolves the
/// RHS in the surrounding scope before the LHS is bound, so the local
/// shadows the outer correctly without self-reference issues.
///
/// `imports` are propagated from the input source files so every type
/// referenced by a binding stays in scope, canonicalised on the way out
/// by ``normalizedImports`` — one internal import per module, whatever
/// access level it was written at. The naive "union all imports"
/// approach can include unrelated imports that happen to live in the
/// same file as a binding — harmless for an internal generated file.
///
/// `bootstrap` is declared `async throws` regardless of whether the
/// current set of bindings actually have async/throws inits. The performance work's
/// lifecycle work makes async/throws constructor injection a
/// first-class option, and locking the signature in now means later
/// migrations don't ripple through every consumer's `try await
/// Wire.bootstrap()` call site. Swift accepts an `async throws`
/// function body that doesn't actually use those capabilities.
package func renderWireGraph(
    imports: [String],
    topologicalOrder: [DiscoveredBinding],
    containerTopologicalOrders: [String: [DiscoveredBinding]] = [:],
    // One entry per `TestingKey` that emits a variant app graph: `<Variant>` → `_<Variant>WireGraph` +
    // `Wire.bootstrap<Variant>()`, over the variant's topological order (production minus the `@BindType`'d/
    // lifted bindings + the contributor proxies). Emitted with the same machinery as container graphs.
    variantAppOrders: [String: [DiscoveredBinding]] = [:],
    seedScopeOrders: [SeedScopeEmission] = [],
    graphConformances: [DiscoveredGraphConformance] = [],
    multibindingKeys: [DiscoveredMultibindingKey] = [],
    syntheticTypeDeclarations: [String] = [],
    existentialPromotions: [ExistentialPromotion] = [],
    // The `@GraphInputs` type, when the module declares one — `Wire.bootstrap(inputs:)`'s parameter type.
    // Only the *default* graph takes it: a container graph is an alternate wiring of the same module, and
    // a seeded scope already has its own entry shape.
    graphInputsType: String? = nil,
    // Needed to decide the *home package*, which is what makes an `allowUnused:` binding a root
    // (a library's `allowUnused` keeps only its diagnostic meaning). See `declaredRoots`.
    externalModules: Set<String> = []
) -> String {
    var file = WireFileBuffer()
    // Everything every graph struct in this file shares, named once. See `GraphEmissionContext`.
    let context = GraphEmissionContext(
        seedScopes: seedScopeLookup(seedScopeOrders),
        existentialPromotions: existentialPromotions,
        graphInputsType: graphInputsType,
        graphConformances: graphConformances,
        multibindingKeys: multibindingKeys,
        externalModules: externalModules
    )

    file.lines.append("// Generated by WireGen — do not edit.")

    // Imports — canonicalised (see `normalizedImports`), deduplicated, and sorted for
    // stability across runs.
    let sortedImports = normalizedImports(imports)
    if !sortedImports.isEmpty {
        file.lines.append("")
        file.lines.append(contentsOf: sortedImports)
    }

    // Plugin-synthesised module-scope types (e.g. `@Factory` factory structs).
    // Emitted before the graph structs so the bindings that construct them —
    // registered by the synthesis pass — are in scope. Each is a full declaration.
    for declaration in syntheticTypeDeclarations {
        file.lines.append("")
        file.lines.append(declaration)
    }

    // Default graph — always emitted, even when empty, so consumers
    // can call `Wire.bootstrap()` unconditionally.
    appendStruct(
        structName: "_WireGraph",
        bootstrapFunction: "_wireBootstrap",
        bootstrapMethod: "bootstrap",
        topologicalOrder: topologicalOrder,
        context: context,
        into: &file
    )

    // Per-container graphs and per-`TestingKey` variant app graphs — identical delegation shape to the
    // default (its own struct + `_wireBootstrap<Name>` + `Wire.bootstrap<Name>()`, the name discriminating
    // them at module scope). Container and variant names are disjoint, so one loop over the merge is safe
    // and deterministic. A variant graph is over the *dropped* order (production minus the `@BindType`'d/
    // lifted bindings + contributor proxies), so a mocked eager `@Singleton`/`@Provides` init never runs
    // under `Wire.bootstrap<Variant>()`; a variant seed façade re-points its `wireGraph:` parameter type
    // to this graph (`variantAppGraphReference`).
    appendNamedGraphs(
        container: containerTopologicalOrders,
        variant: variantAppOrders,
        context: context,
        into: &file
    )

    // Per-seed scope graphs. Each emits a `_<Suffix>WireScope` struct
    // whose `bootstrap(seed:wireGraph:)` takes the externally-owned
    // seed value and the wire graph; the body aliases singleton
    // dependencies as locals via the synthetic-borrow bindings, then
    // constructs scope-bound bindings in topological order.
    // A seed scope's `wireGraph:` parameter names its parent graph's concrete type. When that
    // parent lifts generic parameters (an `@Singleton(as:)` opaque binding), the bare struct
    // name doesn't compile — the parameter needs the opaque-erased `_WireGraph<some P>` form.
    // Map each parent graph to its bindings so the opened reference can be computed per scope.
    let parentGraphBindings = bindingsByParentGraph(default: topologicalOrder, containers: containerTopologicalOrders)
    // The whole-scope façade (`_<S>WireScope` + `Wire.bootstrap<S>Scope` + `_wireBootstrap<S>Scope`)
    // is emitted only for a scope **no bridging proxy enters**.
    //
    // A proxy carries a `_wireEnterScope` thunk that constructs the routed subject's own transitive
    // subgraph per request, and the generated witness calls that, never the façade — so wherever
    // a proxy exists the façade is `internal` dead code: a struct and two functions per seed scope, in
    // every consumer with routed controllers. Where no proxy enters a scope the façade is the only way in,
    // and dropping it would make the scope unconstructible, so it stays. That is the dead-code criterion
    // stated exactly, rather than a flag.
    appendSeedScopeFacades(
        seedScopeOrders,
        enteredByProxy: seedsEnteredByProxy(
            in: topologicalOrder + containerTopologicalOrders.values.flatMap { $0 }
        ),
        parentGraphBindings: parentGraphBindings,
        into: &file.lines,
        entries: &file.bootstrapEntries
    )

    // Setter extensions for `@Inject weak var` on actor consumers.
    // Aggregated across every graph + scope so each actor type's
    // setters emit once at module scope, regardless of how many
    // partitions reference it.
    let allBindings =
        topologicalOrder
        + containerTopologicalOrders.values.flatMap { $0 }
        + seedScopeOrders.flatMap { $0.topologicalOrder }
    file.lines.append(contentsOf: renderActorWeakSetterExtensions(for: allBindings))

    // Adapter-declared graph conformances — `extension _WireGraph: <Protocol>` on the default graph and each
    // variant app graph (`apply(variantGraph)` needs the conformance too).
    appendAllGraphConformances(
        graphConformances,
        defaultOrder: topologicalOrder,
        variantAppOrders: variantAppOrders,
        multibindingKeys: multibindingKeys,
        into: &file.lines
    )

    // The `Wire` façade — one uniform, non-generic entry point per graph.
    // Emitted last so it's a single stable trailing block.
    appendWireFacade(file.bootstrapEntries, into: &file.lines)

    // Every graph's stored-property block and memberwise-init call, decided now that the whole
    // file exists and the reads off each graph can be seen. See `resolveStoragePatches`.
    resolveStoragePatches(file.storagePatches, in: &file.lines)

    // Trailing newline at end of file. `appendStruct` is leading-blank
    // only, so the final struct's closing `}` doesn't end the file
    // without it.
    file.lines.append("")

    return file.lines.joined(separator: "\n")
}

/// Emission-side description of one per-seed scope graph. Mirrors
/// the orchestration result's relevant fields: the seed type
/// expression for the bootstrap seed-parameter type, the parent
/// graph type for the bootstrap wire-graph-parameter type
/// (`_WireGraph` for default-graph seeded scopes,
/// `_<Container>WireGraph` for container-scope ones), the identifier
/// suffix for the struct/function names, the topological order over
/// the combined graph, and the borrowed-binding property names so
/// the emitter knows which entries are singletons aliased from the
/// `wireGraph:` bootstrap parameter rather than constructed in place.
package struct SeedScopeEmission: Sendable {
    package let seedTypeExpression: String
    package let identifierSuffix: String
    package let parentGraphType: String
    package let topologicalOrder: [DiscoveredBinding]
    package let borrowedBindingPropertyNames: Set<String>
    /// The resolved producer adjacency for the scope's graph — used by the scope-entry thunk emission to
    /// construct (and tear down) only the bindings reachable from the routed controller (per-root
    /// reachability). Empty means "no pruning" (every scope binding is treated as reachable),
    /// preserving whole-scope behaviour for callers that don't supply edges.
    package let edges: [BindingIdentity: [BindingIdentity]]
    /// The scope graph's rule-3 promotions — an `any P` consumer inside this
    /// scope reading a `some P` producer, whether the producer is scope-bound or
    /// a borrowed singleton. Each scope body binds its own existential aliases;
    /// the parent graph's aliases aren't in scope for the whole-scope façade, and
    /// the thunk's captured ones only exist if the bootstrap body itself promoted.
    package let existentialPromotions: [ExistentialPromotion]
    /// The variant's `_<Key>Doubles` struct type, for a test-graph seed scope holding one or more
    /// `@BindType`d (doubles-sourced) bindings. Non-nil threads a `doubles: <type>` parameter into the
    /// scope's `bootstrap(seed:, <wireGraph>:, doubles:)` — matching the `doubles.<field>` access paths a
    /// substituted binding resolves to. `nil` is a production scope (seed only), whose emission is
    /// unchanged.
    package let doublesType: String?
    /// The variant's doubles fields (slot-identity name + concrete `Mock` type) this scope substitutes. Used
    /// to spell a **lifted opaque** (`some P`) mocked binding concretely: unlike a borrowed opaque axis
    /// (threaded as a scope generic parameter `T0`), a lifted one has no parent axis to thread, and its
    /// double is the concrete `Mock` — so its stored field and any generic consumer's parameter spell the
    /// concrete mock type. Empty for a production scope or a variant with no opaque mocked binding.
    package let doublesFields: [DoublesField]
    /// The opaque-erased **variant app graph** type (`_<Variant>WireGraph<…>`) this variant seed scope's
    /// `bootstrap(seed:wireGraph:doubles:)` façade takes as its `wireGraph:` parameter — set when the key
    /// emits a variant app graph (production minus the `@BindType`'d/lifted bindings, so their eager inits
    /// don't run under the mock). Only the façade's parameter *type* re-points; the borrow *name* stays
    /// `parentGraphType`'s (`_wireGraph`), so the contributor-proxy façades and production façades are
    /// untouched. `nil` → the façade takes `parentGraphType`'s production graph, as before.
    package var variantAppGraphReference: String?

    package init(
        seedTypeExpression: String,
        identifierSuffix: String,
        parentGraphType: String,
        topologicalOrder: [DiscoveredBinding],
        borrowedBindingPropertyNames: Set<String>,
        edges: [BindingIdentity: [BindingIdentity]] = [:],
        existentialPromotions: [ExistentialPromotion] = [],
        doublesType: String? = nil,
        doublesFields: [DoublesField] = [],
        variantAppGraphReference: String? = nil
    ) {
        self.seedTypeExpression = seedTypeExpression
        self.identifierSuffix = identifierSuffix
        self.parentGraphType = parentGraphType
        self.topologicalOrder = topologicalOrder
        self.borrowedBindingPropertyNames = borrowedBindingPropertyNames
        self.edges = edges
        self.existentialPromotions = existentialPromotions
        self.doublesType = doublesType
        self.doublesFields = doublesFields
        self.variantAppGraphReference = variantAppGraphReference
    }
}

/// The stored-property name on `_WireGraph` and the local name in
/// `_wireBootstrap()` for a given binding. Type-derived: bindings are
/// identified by what they produce, not by their source-level
/// declaration name. Keyed bindings append a key-derived suffix so
/// that two providers of the same type with different keys don't
/// collide. See `identifierName(forType:key:)` for the rule.
func propertyName(for binding: DiscoveredBinding) -> String {
    identifierName(forType: binding.boundType, key: binding.keyIdentifier)
}

/// The canonical local/property name for a `(boundType, key?)` pair.
/// Used for both binding declarations and dependency-resolution sites
/// so a keyed dependency points at the matching keyed binding's local.
/// Also called from `Graph.swift` to detect generated-accessor-name
/// collisions before codegen runs.
///
/// Rules:
/// - Unkeyed: `lowerCamel(sanitize(type))` — same as before keys
///   existed.
/// - Keyed: `lowerCamel(sanitize(type)) + "Keyed" + upperCamel(sanitize(key))`.
///
/// The `Keyed` infix is a sentinel segment matching the `Of`/`And`
/// separator pattern already used for generic instantiations
/// (`Repository<TaskTable>` → `RepositoryOfTaskTable`). It pushes the
/// collision space to "type names that literally contain the word
/// `Keyed` in the matching position," which doesn't happen in real
/// code. The verbose readout — `databaseKeyedDatabasePrimary` for
/// `(Database, "Database.primary")` — is a tradeoff: less ergonomic
/// than a stripped form (`databasePrimary`) but unambiguous, and the
/// keyed accessor is rarely the user's primary access path anyway
/// (keyed bindings usually live behind a consumer).
package func identifierName(forType type: String, key: String?) -> String {
    let typeName = lowerCamelCased(sanitizeIdentifier(type))
    guard let key else { return typeName }
    let keySuffix = upperCamelCased(sanitizeKeyComponents(key))
    return typeName + "Keyed" + keySuffix
}

/// Sanitize a key expression for use inside an identifier. Dots are
/// treated as segment separators — the next letter is upper-cased,
/// the dot is dropped. Other non-identifier characters are dropped
/// silently, matching `sanitizeIdentifier`'s posture.
///
///     "primary"            → "primary"
///     "Database.primary"   → "DatabasePrimary"
///     "Module.Database.x"  → "ModuleDatabaseX"
private func sanitizeKeyComponents(_ raw: String) -> String {
    var result = ""
    var capitalizeNext = false
    for char in raw {
        if char == "." {
            capitalizeNext = true
            continue
        }
        guard char.isLetter || char.isNumber || char == "_" else { continue }
        if capitalizeNext {
            result += String(char).uppercased()
            capitalizeNext = false
        } else {
            result.append(char)
        }
    }
    return result
}

/// Uppercase the first character only — the symmetric counterpart to
/// `lowerCamelCased`. Used to make a key suffix capitalised so it
/// reads as a distinct word in the composed identifier
/// (`appName` + `Alternate` → `appNameAlternate`).
private func upperCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.uppercased() + name.dropFirst()
}

/// Conventional name of the setter extension method WireGen
/// synthesises for `@Inject weak var <property>` on an actor host.
/// Class hosts use direct property assignment and don't need this.
/// `_wire` prefix reserves the name space against collisions with
/// user-written members.
private func actorWeakSetterName(forProperty propertyName: String) -> String {
    "_wireSet\(upperCamelCased(propertyName))"
}

/// Emit `extension <Actor> { func _wireSet<Property>(_ value: T) {
/// self.<property> = value } }` blocks for every weak `@Inject`
/// property on an actor host type that appears in the topological
/// order. Direct property assignment from outside an actor's
/// isolation isn't legal Swift, so the setter extension is the
/// language-supported mechanism — the method is implicitly actor-
/// isolated, and codegen's post-init call site invokes it with
/// `await`.
///
/// Deduplicates by `(consumer type, property name)` so a type
/// bound in multiple graph partitions still emits the extension
/// once at the module level. Extensions emit AFTER all struct/
/// bootstrap blocks so the file's main shape (structs first,
/// per-type extensions afterwards) reads top-down.
private func renderActorWeakSetterExtensions(
    for bindings: [DiscoveredBinding]
) -> [String] {
    var seen: Set<String> = []
    var perType: [(typeReference: String, setters: [(name: String, propertyName: String, type: String)])] = []
    var typeIndex: [String: Int] = [:]
    for binding in bindings where binding.consumerIsActor {
        guard case .scopeBound(let scopeBound) = binding else { continue }
        for injection in scopeBound.memberInjections {
            guard case .propertyAssignment(let propertyName) = injection.shape else { continue }
            guard let parameter = injection.parameters.first else { continue }
            let dedupeKey = "\(scopeBound.qualifiedTypeName)::\(propertyName)"
            guard !seen.contains(dedupeKey) else { continue }
            seen.insert(dedupeKey)
            let setter = (
                name: actorWeakSetterName(forProperty: propertyName),
                propertyName: propertyName,
                type: parameter.type
            )
            if let index = typeIndex[scopeBound.qualifiedTypeName] {
                perType[index].setters.append(setter)
            } else {
                typeIndex[scopeBound.qualifiedTypeName] = perType.count
                perType.append((scopeBound.qualifiedTypeName, [setter]))
            }
        }
    }
    var lines: [String] = []
    for entry in perType {
        lines.append("")
        lines.append("extension \(entry.typeReference) {")
        for setter in entry.setters {
            lines.append("    func \(setter.name)(_ value: \(setter.type)) {")
            lines.append("        self.\(setter.propertyName) = value")
            lines.append("    }")
        }
        lines.append("}")
    }
    return lines
}

/// The RHS expression that constructs a single binding inside
/// `bootstrap()`. Uses bare references — the consumer's source-file
/// imports are propagated to the generated file so user-supplied
/// symbols are in scope without qualification.
///
/// `resolvingLocal` is forwarded to `renderArguments` so per-graph
/// dependency substitutions (e.g., the seed-scope path inlining
/// borrowed singletons at use sites) flow through.
func constructionExpression(
    for binding: DiscoveredBinding,
    resolvingLocal: ((String) -> String?)? = nil
) -> String {
    switch binding {
    case .scopeBound(let scopeBound):
        // Generic instantiations (`Repository<TaskTable>`) keep their
        // angle brackets at the call site since Swift's syntax accepts
        // that. `qualifiedTypeName` includes any enclosing-type
        // prefix (e.g. `TestContainer.MockService`) so a `@Singleton`
        // nested inside a `@Container` resolves correctly when called
        // from the module-scope `_wireBootstrap...` free function.
        let args = renderArguments(scopeBound.dependencies, consumer: binding, resolvingLocal: resolvingLocal)
        let call = "\(scopeBound.qualifiedTypeName)(\(args))"
        return effectPrefix(
            isAsync: scopeBound.initIsAsync,
            isThrowing: scopeBound.initIsThrowing
        ) + call
    case .provider(let provider):
        let prefix = effectPrefix(
            isAsync: provider.isAsync,
            isThrowing: provider.isThrowing
        )
        switch provider.form {
        case .property:
            return prefix + provider.accessPath
        case .function:
            let args = renderArguments(provider.dependencies, consumer: binding, resolvingLocal: resolvingLocal)
            // Always a bare call: Swift forbids explicit specialisation of a
            // function (`makeRepo<DynamoDBTable>()` is illegal — unlike a type
            // initialiser). A specialised generic provider function infers its
            // type arguments instead — from its value arguments, or from the
            // concrete-return-typed local `appendStruct` annotates.
            return "\(prefix)\(provider.accessPath)(\(args))"
        }
    case .aggregate(let aggregate):
        return aggregateConstruction(aggregate, resolvingLocal: resolvingLocal)
    }
}

/// Emit an aggregate's construction: a collection literal over the
/// contributor locals, coerced to the declared collection type so the
/// heterogeneous concrete elements unify (`[a, b] as [any P]`). Each
/// contributor is referenced by the same local name its own binding
/// emits. The builder fold lands in Step 5b.
private func aggregateConstruction(
    _ aggregate: DiscoveredAggregate,
    resolvingLocal: ((String) -> String?)?
) -> String {
    func local(for contributor: AggregateContributor) -> String {
        let name = identifierName(
            forType: contributor.dependency.type,
            key: contributor.dependency.keyIdentifier
        )
        return resolvingLocal?(name) ?? name
    }
    switch aggregate.flavour {
    case .collected:
        let elements = aggregate.contributors.map(local).joined(separator: ", ")
        return "[\(elements)] as \(aggregate.collectionType)"
    case .mapped:
        if aggregate.contributors.isEmpty {
            return "[:] as \(aggregate.collectionType)"
        }
        let pairs = aggregate.contributors.map { contributor in
            "\(contributor.mapKeyExpression ?? "_"): \(local(for: contributor))"
        }.joined(separator: ", ")
        return "[\(pairs)] as \(aggregate.collectionType)"
    case .builder:
        // Builder aggregates are emitted by `builderFoldLines` in the
        // bootstrap body (a local function + call), not as a single
        // expression, so this is never reached.
        preconditionFailure("builder aggregate is emitted via builderFoldLines")
    }
}

/// Emit a builder aggregate as a `@resultBuilder`-annotated local
/// function listing the contributor locals in order, followed by its
/// invocation binding the aggregate local. The function captures the
/// already-constructed contributor locals (topological order guarantees
/// they precede the aggregate), so it takes no parameters.
func builderFoldLines(_ aggregate: DiscoveredAggregate) -> [String] {
    let aggregateLocal = identifierName(forType: aggregate.collectionType, key: aggregate.keyReference)
    let foldName = "_wireFold" + upperCamelCased(sanitizeKeyComponents(aggregate.keyReference))
    let builderType = aggregate.builderTypeName ?? ""
    var lines = [
        "    @\(builderType)",
        "    func \(foldName)() -> \(aggregate.collectionType) {",
    ]
    for contributor in aggregate.contributors {
        let local = identifierName(
            forType: contributor.dependency.type,
            key: contributor.dependency.keyIdentifier
        )
        lines.append("        \(local)")
    }
    lines.append("    }")
    lines.append("    let \(aggregateLocal) = \(foldName)()")
    return lines
}

/// Combine `isAsync` / `isThrowing` into the call-site prefix Swift
/// expects on an effectful call expression. Returns an empty string
/// for sync, non-throwing calls so the construction expression stays
/// `Type(args)` shape; otherwise returns `"try "`, `"await "`, or
/// `"try await "`. The enclosing bootstrap function is `async
/// throws` (the widest contract) so any combination is permitted
/// at the call site.
func effectPrefix(isAsync: Bool, isThrowing: Bool) -> String {
    switch (isThrowing, isAsync) {
    case (false, false): return ""
    case (true, false): return "try "
    case (false, true): return "await "
    case (true, true): return "try await "
    }
}

/// Render a constructor's argument list. Each dependency is resolved
/// to the local-name for its `(type, key?)` identity; the argument
/// label comes from the dependency's external label (or is omitted
/// entirely for wildcard labels).
///
/// `resolvingLocal`, when supplied, lets a caller substitute an
/// expression for the local-name. The seed-scope emission uses this
/// to inline borrowed singletons at the use site (`_WireGraph.logger`
/// instead of `logger`) without first declaring a local. Returning
/// `nil` from the closure falls back to the standard local-name
/// behaviour.
private func renderArguments(
    _ dependencies: [DependencyParameter],
    consumer: DiscoveredBinding? = nil,
    resolvingLocal: ((String) -> String?)? = nil
) -> String {
    dependencies
        // Capture dependencies order the consumer but pass no argument — the scope-entry thunk that
        // uses them references the captured locals directly. See `DependencyKind.scopeCapture`.
        .filter { $0.kind != .scopeCapture }
        .map { dependency in
            // Resolve against the bridged identity so a constrained-parameter
            // dependency (`table: Table`) references its `some P` producer's
            // local (`someDBTable`), not a `table` local that doesn't exist.
            // For every other dependency this is its own identity, unchanged.
            let identity = consumer.map { bridgedDependencyIdentity(dependency, in: $0) } ?? dependency.identity
            let localName = identifierName(forType: identity.displayType, key: identity.key)
            let value = resolvingLocal?(localName) ?? localName
            if let label = dependency.name {
                return "\(label): \(value)"
            }
            // Wildcard external label — the call site omits it entirely.
            return value
        }.joined(separator: ", ")
}

/// The graph-binding local names a bridging contributor proxy's construction references beyond its
/// scope-entry thunk — its lifted input edges (each `@Factory`-synthesised `_wireFactory_<key>` dependency
/// and each adapter `@X(T.self)` / `@X(key)` dependency), resolved to the property names they carry on the
/// graph (the same names `renderArguments` produces for the construction, and that the graph stores them
/// under). The contributor-proxy facade binds each as `let <local> = _wireGraph.<local>` before constructing
/// the variant proxy, so the bare reference in the construction resolves to the graph's instance, not the
/// type. Empty for a proxy with no lifted input edges. Deterministic in dependency order.
func proxyGraphDependencyLocals(for proxy: DiscoveredScopeBoundType) -> [String] {
    proxy.dependencies.compactMap { dependency in
        // The subject (positional, `name == nil`) and the scope-entry thunk / capture deps are not graph
        // bindings the facade borrows: the subject arrives via the thunk, and capture deps pass no argument.
        guard dependency.kind == .injectInitParameter, dependency.name != nil else { return nil }
        let identity = bridgedDependencyIdentity(dependency, in: .scopeBound(proxy))
        return identifierName(forType: identity.displayType, key: identity.key)
    }
}

/// Emit the post-construction member-injection block for every
/// binding in the topological order. Each `MemberInjection`
/// renders to one source line — either a property assignment
/// (`consumer.prop = parameter`) or a method call
/// (`[try] [await] consumer.method(args...)`), chosen by the
/// injection's `Shape`.
///
/// The block emits *after* all construction lines so every target
/// reference is in scope as a local. Cycle-breaking comes from
/// this two-phase structure: the graph's init-time-edge topo sort
/// decides construction order, and the member-injection block
/// closes any post-construction wiring (including cycles whose
/// other side is a weak ref or a setter method).
///
/// `resolvingLocal`, when supplied, lets the seed-scope path
/// inline borrowed singletons at the target reference — same
/// callback shape as `renderArguments`. A member injection
/// parameter pointing at a borrowed binding resolves through the
/// borrow's `_WireGraph.foo` access path rather than a local.
///
/// `skipConsumers` excludes bindings that aren't constructed in
/// the current scope (e.g. borrowed singletons inside a seed
/// scope's bootstrap). Their post-init wiring belongs to whichever
/// scope owns their construction, not to scopes that merely
/// reference them.
func renderMemberInjections(
    for topologicalOrder: [DiscoveredBinding],
    resolvingLocal: ((String) -> String?)? = nil,
    skipConsumers: Set<String> = []
) -> [String] {
    var lines: [String] = []
    for binding in topologicalOrder {
        let consumerLocal = propertyName(for: binding)
        if skipConsumers.contains(consumerLocal) { continue }
        for injection in binding.memberInjections {
            let args = renderArguments(injection.parameters, consumer: binding, resolvingLocal: resolvingLocal)
            switch injection.shape {
            case .propertyAssignment(let propertyName):
                // Sugar form for `@Inject weak var`. For class
                // consumers, direct property assignment is the
                // natural Swift idiom — zero-overhead and lines up
                // with what the user would have written manually.
                // For actor consumers, direct assignment from
                // outside isolation isn't legal Swift; codegen
                // routes the write through a synthesised setter
                // extension method (`_wireSet<Property>`) emitted
                // elsewhere in the generated file, and the call
                // crosses isolation via `await`.
                if binding.consumerIsActor {
                    let setterName = actorWeakSetterName(forProperty: propertyName)
                    lines.append("    await \(consumerLocal).\(setterName)(\(args))")
                } else {
                    lines.append("    \(consumerLocal).\(propertyName) = \(args)")
                }
            case .methodCall(let methodName):
                // General form: user-written method, may have any
                // effect colour. The prefix combines the method's
                // own effects with the consumer's isolation: calling
                // any method on an actor from outside its isolation
                // requires `await` regardless of whether the method
                // itself is declared `async` (the await pays for the
                // isolation crossing, not for the method's
                // asynchrony). `consumerIsActor` folds into `isAsync`
                // at the call site so `effectPrefix` stays
                // single-purpose.
                let prefix = effectPrefix(
                    isAsync: injection.isAsync || binding.consumerIsActor,
                    isThrowing: injection.isThrowing
                )
                lines.append("    \(prefix)\(consumerLocal).\(methodName)(\(args))")
            }
        }
    }
    return lines
}

/// Strip a type expression down to a Swift-identifier-safe form for
/// use as a property/local name. Generic instantiations are encoded
/// with `Of` and `And` separators so distinct instantiations of the
/// same base type produce distinct names:
///
///     Repository<TaskTable>          → RepositoryOfTaskTable
///     Repository<Foo, Bar<Baz>>      → RepositoryOfFooAndBarOfBaz
///     any Logger                      → anyLogger
///
/// Other special-character cases (function types, optionals, tuples,
/// etc.) drop non-identifier characters; if a future user trips over
/// a collision (two distinct bound types that sanitize to the same
/// identifier), iteration 3's diagnostic pass will detect it. Until
/// then the recommended fix is a typealias.
package func sanitizeIdentifier(_ raw: String) -> String {
    var result = ""
    // Upper-camel the first letter after an `Of`/`And` boundary so the segment
    // reads as camelCase — `Controller<some TaskRepo>` →
    // `ControllerOfSomeTaskRepo`, not `...OfsomeTaskRepo`. Concrete type
    // arguments already start uppercase, so only `some`/`any` change.
    var capitalizeNext = false
    for char in raw {
        switch char {
        case "<":
            result += "Of"
            capitalizeNext = true
        case ",":
            result += "And"
            capitalizeNext = true
        case _ where char.isLetter || char.isNumber || char == "_":
            result += capitalizeNext ? char.uppercased() : String(char)
            capitalizeNext = false
        default:
            // Everything else (whitespace, `>`, `?`, `!`, `[`, `]`,
            // `&`, `:`, `.`, `(`, `)`, `->`) is dropped silently.
            break
        }
    }
    return result
}

/// Lowercase the first character only — `B` → `b`, `TaskRepository` →
/// `taskRepository`, `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
/// The simplest convention that produces unambiguous, distinct names.
/// More sophisticated acronym-aware casing (`URLSession` →
/// `urlSession`) can be added later if generated names look awkward
/// enough to bother with.
private func lowerCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.lowercased() + name.dropFirst()
}

/// The seeds a bridging contributor proxy enters — read off the `_wireEnterScope` thunk each one carries.
func seedsEnteredByProxy(in bindings: [DiscoveredBinding]) -> Set<String> {
    Set(bindings.flatMap { $0.dependencies.compactMap { $0.scopeEntry?.seed } })
}

/// Emit the whole-scope façade — `_<S>WireScope` plus `_wireBootstrap<S>Scope` plus the `Wire` entry —
/// for each seed scope **no bridging proxy enters**.
///
/// A proxy carries a `_wireEnterScope` thunk that constructs the routed subject's own transitive subgraph
/// per request, and the generated witness calls that, never the façade. So wherever a proxy
/// exists the façade is `internal` dead code — a struct and two functions per seed scope, in every
/// consumer with routed controllers. Where no proxy enters a scope the façade is the only way in, and
/// dropping it would make the scope unconstructible, so it stays. That is the dead-code criterion stated
/// exactly rather than approximated by a flag, and it is why swift-wire's own seed-scope tests keep
/// working: their scopes have no proxies.
private func appendSeedScopeFacades(
    _ seedScopeOrders: [SeedScopeEmission],
    enteredByProxy: Set<String>,
    parentGraphBindings: [String: [DiscoveredBinding]],
    into lines: inout [String],
    entries bootstrapEntries: inout [BootstrapEntry]
) {
    for scope in seedScopeOrders.sorted(by: { $0.identifierSuffix < $1.identifierSuffix })
    where !enteredByProxy.contains(scope.seedTypeExpression) {
        // A variant seed scope's façade takes its variant app graph (`_<Variant>WireGraph<…>`) — dropped
        // `@BindType`'d/lifted bindings, so their eager inits don't run under the mock — while its borrow
        // name stays `parentGraphType`'s (`_wireGraph`). Production/keyless scopes use the derived reference.
        let parentGraphTypeReference =
            scope.variantAppGraphReference
            ?? openGraphTypeReference(
                structName: scope.parentGraphType,
                topologicalOrder: parentGraphBindings[scope.parentGraphType] ?? []
            )
        appendSeedScopeStruct(
            scope: scope,
            parentGraphTypeReference: parentGraphTypeReference,
            into: &lines,
            entries: &bootstrapEntries
        )
    }
}
